/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidade.fatec;

import javax.swing.table.DefaultTableModel;



/**
 *
 * @author m_sal
 */
public class ContabilidadePanelResult extends javax.swing.JFrame {

    /**
     * Creates new form ContabilidadePanelResult
     */
        DefaultTableModel model;
        DefaultTableModel model2;
    
    public ContabilidadePanelResult() {
        
        initComponents();
        model=(DefaultTableModel)jTEmpresa.getModel();
        model2=(DefaultTableModel)jTResumo.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTEmpresa = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResumo = new javax.swing.JTable();
        jbtVoltar = new javax.swing.JButton();
        jbtnMostrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultados");

        jTEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lançamento", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTEmpresa);

        jTResumo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTResumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dependente", "Salario Bruto", "VT", "INSS", "IRRF", "Salario Liqido", "FGTS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResumo);

        jbtVoltar.setText("Voltar");
        jbtVoltar.setToolTipText("Voltar a tela anterior");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jbtnMostrar.setText("Mostrar");
        jbtnMostrar.setToolTipText("Monstrar dados na tabela");
        jbtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.setToolTipText("Limpar dados carregados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jbtVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtVoltar)
                    .addComponent(jbtnMostrar)
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
        // TODO add your handling code here:
        model2.insertRow(model2.getRowCount(), new Object[]{nome[0].toString(), dependentes[0],salario[0],vt[0],inss[0],irrf[0],liquido[0],fgts[0]});
        model2.insertRow(model2.getRowCount(), new Object[]{nome[1].toString(), dependentes[1],salario[1],vt[1],inss[1],irrf[1],liquido[1],fgts[1]});
        model2.insertRow(model2.getRowCount(), new Object[]{nome[2].toString(), dependentes[2],salario[2],vt[2],inss[2],irrf[2],liquido[2],fgts[2]});
        model2.insertRow(model2.getRowCount(), new Object[]{nome[3].toString(), dependentes[3],salario[3],vt[3],inss[3],irrf[3],liquido[3],fgts[3]});
        model2.insertRow(model2.getRowCount(), new Object[]{nome[4].toString(), dependentes[4],salario[4],vt[4],inss[4],irrf[4],liquido[4],fgts[4]});
//      
        CalcularFolha.Arredondar arredonda = new CalcularFolha.Arredondar();       
        totGeral =  arredonda.converterDoisDecimais(inssPatronal +  totINSS +   totIRRF + totFGTS + totLiquido) ;
       
        
       // model.insertRow(model.getRowCount(), new Object[]{"Salario Bruto Total",  totSalBruto });
        model.insertRow(model.getRowCount(), new Object[]{"INSS Patronal",  inssPatronal });
        model.insertRow(model.getRowCount(), new Object[]{"INSS ",  totINSS });
        model.insertRow(model.getRowCount(), new Object[]{"IRRF ",  totIRRF });
        model.insertRow(model.getRowCount(), new Object[]{"FGTS ",  totFGTS });
        model.insertRow(model.getRowCount(), new Object[]{"Salario Liquido ",  totLiquido });
        model.insertRow(model.getRowCount(), new Object[]{"Total ",  totGeral });
        
        
        
        ContabilidadePanelResult.totLiquido = totLiquido;
        
        
        jbtnMostrar.setEnabled(false);
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int qtd = model2.getRowCount();
        
        for (int i = qtd - 1; i >= 0; i--) {
            model2.removeRow(i);
        }
        jbtnMostrar.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Colocar aqui todas as variaveis que sera carregado no principal para carga do form 
    
    public static double[] salario = new double[5]; 
    public static String[] nome = new String[5];
    public static int[] dependentes = new int[5]; 
    public static double[] vt  =  new double[5];
    public static double[] inss = new double[5];
    public static double[] irrf = new double[5];
    public static double[] liquido = new double[5];
    public static double[] fgts = new double[5];
    
    public static double inssPatronal = 0; //
    public static double totSalBruto = 0;//
    public static double totINSS = 0;
    public static double totIRRF = 0;
    public static double totLiquido = 0;
    public static double totFGTS = 0;
    double totGeral=0;
    
    
    
    
    
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanelResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanelResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanelResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanelResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContabilidadePanelResult().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTEmpresa;
    public javax.swing.JTable jTResumo;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JButton jbtnMostrar;
    // End of variables declaration//GEN-END:variables
}
