/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidade.fatec;




/**
 *
 * @author m_sal
 */
public class ContabilidadePanel extends javax.swing.JFrame {

    /**
     * Creates new form ContabilidadePanel
     */
    public ContabilidadePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new java.awt.Label();
        lblSalario = new java.awt.Label();
        lblVT = new java.awt.Label();
        lblDependentes = new java.awt.Label();
        jTNome1 = new javax.swing.JTextField();
        jFSalario1 = new javax.swing.JFormattedTextField();
        cbVT1 = new java.awt.Checkbox();
        jFDependentes1 = new javax.swing.JFormattedTextField();
        jTNome2 = new javax.swing.JTextField();
        jFSalario2 = new javax.swing.JFormattedTextField();
        cbVT2 = new java.awt.Checkbox();
        jFDependentes2 = new javax.swing.JFormattedTextField();
        jTNome3 = new javax.swing.JTextField();
        jFSalario3 = new javax.swing.JFormattedTextField();
        cbVT3 = new java.awt.Checkbox();
        jFDependentes3 = new javax.swing.JFormattedTextField();
        jTNome4 = new javax.swing.JTextField();
        jFSalario4 = new javax.swing.JFormattedTextField();
        cbVT4 = new java.awt.Checkbox();
        jFDependentes4 = new javax.swing.JFormattedTextField();
        jTNome5 = new javax.swing.JTextField();
        jFSalario5 = new javax.swing.JFormattedTextField();
        cbVT5 = new java.awt.Checkbox();
        jFDependentes5 = new javax.swing.JFormattedTextField();
        jbtnMostrar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        jbtnProcessar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular Folha de Pagamento");

        lblNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNome.setText("Nome");

        lblSalario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSalario.setText("Salário");

        lblVT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblVT.setText("VT");

        lblDependentes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDependentes.setText("Dependentes");

        jFSalario1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFDependentes1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFSalario2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFDependentes2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFSalario3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFDependentes3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFSalario4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFDependentes4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFSalario5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFDependentes5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jbtnMostrar.setText("Mostrar Resultado");
        jbtnMostrar.setEnabled(false);
        jbtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarActionPerformed(evt);
            }
        });

        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        jbtnProcessar.setText("Processar");
        jbtnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTNome2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFSalario2)
                                    .addComponent(jFSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jFSalario3)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(281, 281, 281)
                                .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFSalario5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(jFSalario4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFDependentes2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFDependentes4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFDependentes5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFDependentes1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jFDependentes3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jbtnProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFDependentes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbVT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFDependentes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFDependentes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFSalario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFSalario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFDependentes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFDependentes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFSalario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMostrar)
                    .addComponent(jbtnSair)
                    .addComponent(jbtnProcessar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblSalario.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
        // TODO add your handling code here:
        ContabilidadePanelResult resultado = new ContabilidadePanelResult();
        resultado.setVisible(true);
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jbtnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcessarActionPerformed
        // TODO add your handling code here:
    
        
        
        CalcularFolha.CalcularINSS inss =  new CalcularFolha.CalcularINSS();
        CalcularFolha.CalculaBaseDeCalculo base = new CalcularFolha.CalculaBaseDeCalculo();
        CalcularFolha.CalcIRRF imposto = new CalcularFolha.CalcIRRF();
        CalcularFolha.Arredondar arredonda = new CalcularFolha.Arredondar();
        double cINSS = 0;
        double cBase=0;
        double cVT=0;
        double cFGTS=0;
        double cDep=0;
        double cImposto=0;
        double cLiquido=0;
        
        double totSal=0;
        double totImposto=0;
        double totFGTS=0;
        double totINSS=0;
        double totPatronal=0;
        double totLiquido=0;
        
             
            for(int i=0 ; i < 5; i++){
                switch(i){
                  case 0:
                      ContabilidadePanelResult.nome[i] = jTNome1.getText();
                      ContabilidadePanelResult.salario[i] = Double.parseDouble(jFSalario1.getText().replace(",","."));
                      cFGTS =  Double.parseDouble(jFSalario1.getText().replace(",", ".")) * 0.08;
                      ContabilidadePanelResult.fgts[i] = arredonda.converterDoisDecimais(cFGTS) ;
                      
                      
                      cINSS =  inss.calculaINSS(Double.parseDouble(jFSalario1.getText().replace(",", ".")));
                      ContabilidadePanelResult.inss[i] = arredonda.converterDoisDecimais(cINSS);
                      
                      cDep = inss.calcDep(Integer.parseInt(jFDependentes1.getText()));
                      cBase = base.calcularBase(Double.parseDouble(jFSalario1.getText().replace(",", ".")), cINSS,cDep);
                      cImposto =imposto.CalcularIRRF(cBase);
                      ContabilidadePanelResult.irrf[i] = arredonda.converterDoisDecimais(cImposto);
                      
                      
                      if (cbVT1.getState() == true ){
                          cVT = Double.parseDouble(jFSalario1.getText().replace(",", ".")) * 0.06;
                          if (cVT > 220){
                              cVT = 220.0;
                          }
                      }
                      
                      ContabilidadePanelResult.liquido[i] = arredonda.converterDoisDecimais(Double.parseDouble(jFSalario1.getText().replace(",", ".")) 
                              - cINSS - cVT - ContabilidadePanelResult.irrf[i]);
                      ContabilidadePanelResult.vt[i] = arredonda.converterDoisDecimais(cVT);
                      ContabilidadePanelResult.dependentes[i] = Integer.parseInt(jFDependentes1.getText());
                      cLiquido =
                              ContabilidadePanelResult.salario[i] - 
                              ContabilidadePanelResult.vt[i]  -
                              ContabilidadePanelResult.inss[i] - 
                              ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.liquido[i] = arredonda.converterDoisDecimais(cLiquido); 
                      
                      totSal += Double.parseDouble(jFSalario1.getText().replace(",", "."));
                      totImposto += cImposto;
                      totFGTS += cFGTS;
                      totINSS += cINSS;
                      totLiquido += cLiquido;        
                              
                      break;
                  case 1:
                      ContabilidadePanelResult.nome[i] = jTNome2.getText();
                      ContabilidadePanelResult.salario[i] = Double.parseDouble(jFSalario2.getText().replace(",","."));
                      cFGTS = Double.parseDouble(jFSalario2.getText().replace(",", ".")) * 0.08;
                      ContabilidadePanelResult.fgts[i] =arredonda.converterDoisDecimais(cFGTS) ;
                      
                      
                      cINSS =  inss.calculaINSS(Double.parseDouble(jFSalario2.getText().replace(",", ".")));
                      ContabilidadePanelResult.inss[i] = arredonda.converterDoisDecimais(cINSS);
                      
                      cDep = inss.calcDep(Integer.parseInt(jFDependentes2.getText()));
                      cBase = base.calcularBase(Double.parseDouble(jFSalario2.getText().replace(",", ".")), cINSS,cDep);
                      cImposto =imposto.CalcularIRRF(cBase);
                      ContabilidadePanelResult.irrf[i] =arredonda.converterDoisDecimais(cImposto);
                      
                      
                      if (cbVT2.getState() == true ){
                          cVT = Double.parseDouble(jFSalario2.getText().replace(",", ".")) * 0.06;
                          if (cVT > 220){
                              cVT = 220.0;
                          }
                      }
                      
                      ContabilidadePanelResult.liquido[i] = Double.parseDouble(jFSalario2.getText().replace(",", ".")) 
                              - cINSS - cVT - ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.vt[i] = arredonda.converterDoisDecimais(cVT);
                      ContabilidadePanelResult.dependentes[i] = Integer.parseInt(jFDependentes2.getText());
                      cLiquido =
                              ContabilidadePanelResult.salario[i] - 
                              ContabilidadePanelResult.vt[i]  -
                              ContabilidadePanelResult.inss[i] - 
                              ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.liquido[i] = arredonda.converterDoisDecimais(cLiquido); 
                      
                      totSal += Double.parseDouble(jFSalario2.getText().replace(",", "."));
                      totImposto += cImposto;
                      totFGTS += cFGTS;
                      totINSS += cINSS;
                      totLiquido += cLiquido;                        
                      break;
                      
                  case 2:
                      ContabilidadePanelResult.nome[i] = jTNome3.getText();
                      ContabilidadePanelResult.salario[i] = Double.parseDouble(jFSalario3.getText().replace(",","."));
                      cFGTS = Double.parseDouble(jFSalario3.getText().replace(",", ".")) * 0.08;
                      ContabilidadePanelResult.fgts[i] =arredonda.converterDoisDecimais(cFGTS) ;
                      
                      
                      cINSS =  inss.calculaINSS(Double.parseDouble(jFSalario3.getText().replace(",", ".")));
                      ContabilidadePanelResult.inss[i] = arredonda.converterDoisDecimais(cINSS);
                      
                      cDep = inss.calcDep(Integer.parseInt(jFDependentes3.getText()));
                      cBase = base.calcularBase(Double.parseDouble(jFSalario3.getText().replace(",", ".")), cINSS,cDep);
                      cImposto =imposto.CalcularIRRF(cBase);
                      ContabilidadePanelResult.irrf[i] = arredonda.converterDoisDecimais(cImposto);
                      
                      
                      if (cbVT2.getState() == true ){
                          cVT = Double.parseDouble(jFSalario3.getText().replace(",", ".")) * 0.06;
                          if (cVT > 220){
                              cVT = 220.0;
                          }
                      }
                      
                      ContabilidadePanelResult.liquido[i] = Double.parseDouble(jFSalario3.getText().replace(",", ".")) 
                              - cINSS - cVT - ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.vt[i] = arredonda.converterDoisDecimais(cVT);
                      ContabilidadePanelResult.dependentes[i] = Integer.parseInt(jFDependentes3.getText());
                      cLiquido =
                              ContabilidadePanelResult.salario[i] - 
                              ContabilidadePanelResult.vt[i]  -
                              ContabilidadePanelResult.inss[i] - 
                              ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.liquido[i] = arredonda.converterDoisDecimais(cLiquido); 
                      
                      totSal += Double.parseDouble(jFSalario3.getText().replace(",", "."));
                      totImposto += cImposto;
                      totFGTS += cFGTS;
                      totINSS += cINSS;
                      totLiquido += cLiquido;                        
  
                      
                      
                      break;
                  case 3:
                    ContabilidadePanelResult.nome[i] = jTNome4.getText();
                      ContabilidadePanelResult.salario[i] = Double.parseDouble(jFSalario4.getText().replace(",","."));
                      cFGTS = Double.parseDouble(jFSalario4.getText().replace(",", ".")) * 0.08;
                      ContabilidadePanelResult.fgts[i] =arredonda.converterDoisDecimais(cFGTS) ;
                      
                      
                      cINSS =  inss.calculaINSS(Double.parseDouble(jFSalario4.getText().replace(",", ".")));
                      ContabilidadePanelResult.inss[i] = arredonda.converterDoisDecimais(cINSS);
                      
                      cDep = inss.calcDep(Integer.parseInt(jFDependentes4.getText()));
                      cBase = base.calcularBase(Double.parseDouble(jFSalario4.getText().replace(",", ".")), cINSS,cDep);
                      cImposto =imposto.CalcularIRRF(cBase);
                      ContabilidadePanelResult.irrf[i] = arredonda.converterDoisDecimais(cImposto);
                      
                      
                      if (cbVT2.getState() == true ){
                          cVT = Double.parseDouble(jFSalario4.getText().replace(",", ".")) * 0.06;
                          if (cVT > 220){
                              cVT = 220.0;
                          }
                      }
                      
                      ContabilidadePanelResult.liquido[i] = Double.parseDouble(jFSalario4.getText().replace(",", ".")) 
                              - cINSS - cVT - ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.vt[i] = arredonda.converterDoisDecimais(cVT);
                      ContabilidadePanelResult.dependentes[i] = Integer.parseInt(jFDependentes4.getText());
                      cLiquido =
                              ContabilidadePanelResult.salario[i] - 
                              ContabilidadePanelResult.vt[i]  -
                              ContabilidadePanelResult.inss[i] - 
                              ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.liquido[i] = arredonda.converterDoisDecimais(cLiquido); 
                      
                      totSal += Double.parseDouble(jFSalario4.getText().replace(",", "."));
                      totImposto += cImposto;
                      totFGTS += cFGTS;
                      totINSS += cINSS;
                      totLiquido += cLiquido;                        
                        
                      
                      
                      
                      
                      break;
                  case 4:
                      ContabilidadePanelResult.nome[i] = jTNome5.getText();
                      ContabilidadePanelResult.salario[i] = Double.parseDouble(jFSalario5.getText().replace(",","."));
                      cFGTS = Double.parseDouble(jFSalario5.getText().replace(",", ".")) * 0.08;
                      ContabilidadePanelResult.fgts[i] =arredonda.converterDoisDecimais(cFGTS) ;
                      
                      
                      cINSS =  inss.calculaINSS(Double.parseDouble(jFSalario5.getText().replace(",", ".")));
                      ContabilidadePanelResult.inss[i] = arredonda.converterDoisDecimais(cINSS);
                      
                      cDep = inss.calcDep(Integer.parseInt(jFDependentes5.getText()));
                      cBase = base.calcularBase(Double.parseDouble(jFSalario5.getText().replace(",", ".")), cINSS,cDep);
                      cImposto =imposto.CalcularIRRF(cBase);
                      ContabilidadePanelResult.irrf[i] = arredonda.converterDoisDecimais(cImposto);
                      
                      
                      if (cbVT2.getState() == true ){
                          cVT = Double.parseDouble(jFSalario5.getText().replace(",", ".")) * 0.06;
                          if (cVT > 220){
                              cVT = 220.0;
                          }
                      }
                      
                      ContabilidadePanelResult.liquido[i] = Double.parseDouble(jFSalario5.getText().replace(",", ".")) 
                              - cINSS - cVT - ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.vt[i] = arredonda.converterDoisDecimais(cVT);
                      ContabilidadePanelResult.dependentes[i] = Integer.parseInt(jFDependentes5.getText());
                      cLiquido =
                              ContabilidadePanelResult.salario[i] - 
                              ContabilidadePanelResult.vt[i]  -
                              ContabilidadePanelResult.inss[i] - 
                              ContabilidadePanelResult.irrf[i];
                      ContabilidadePanelResult.liquido[i] = arredonda.converterDoisDecimais(cLiquido); 
                      
                      totSal +=  Double.parseDouble(jFSalario5.getText().replace(",", "."));
                      totImposto += cImposto;
                      totFGTS += cFGTS;
                      totINSS += cINSS;
                      totLiquido += cLiquido;                        
  
                      
                      break;
                       
                }
            }
        ContabilidadePanelResult.totSalBruto = arredonda.converterDoisDecimais(totSal);
        ContabilidadePanelResult.inssPatronal = arredonda.converterDoisDecimais(totSal * 0.278);
        ContabilidadePanelResult.totINSS = arredonda.converterDoisDecimais(totINSS);
        ContabilidadePanelResult.totIRRF = arredonda.converterDoisDecimais(totImposto);
        ContabilidadePanelResult.totLiquido = arredonda.converterDoisDecimais(totLiquido);
        ContabilidadePanelResult.totFGTS = arredonda.converterDoisDecimais(totFGTS);

        
        
        
//        btnProcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
//        try {
//            new Thread().sleep(1000);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(ContabilidadePanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        jbtnMostrar.setEnabled(true);
        
        
//  
    }//GEN-LAST:event_jbtnProcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContabilidadePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ContabilidadePanel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox cbVT1;
    private java.awt.Checkbox cbVT2;
    private java.awt.Checkbox cbVT3;
    private java.awt.Checkbox cbVT4;
    private java.awt.Checkbox cbVT5;
    private javax.swing.JFormattedTextField jFDependentes1;
    private javax.swing.JFormattedTextField jFDependentes2;
    private javax.swing.JFormattedTextField jFDependentes3;
    private javax.swing.JFormattedTextField jFDependentes4;
    private javax.swing.JFormattedTextField jFDependentes5;
    private javax.swing.JFormattedTextField jFSalario1;
    private javax.swing.JFormattedTextField jFSalario2;
    private javax.swing.JFormattedTextField jFSalario3;
    private javax.swing.JFormattedTextField jFSalario4;
    private javax.swing.JFormattedTextField jFSalario5;
    private javax.swing.JTextField jTNome1;
    private javax.swing.JTextField jTNome2;
    private javax.swing.JTextField jTNome3;
    private javax.swing.JTextField jTNome4;
    private javax.swing.JTextField jTNome5;
    private javax.swing.JButton jbtnMostrar;
    private javax.swing.JButton jbtnProcessar;
    private javax.swing.JButton jbtnSair;
    private java.awt.Label lblDependentes;
    private java.awt.Label lblNome;
    private java.awt.Label lblSalario;
    private java.awt.Label lblVT;
    // End of variables declaration//GEN-END:variables
}
